apiVersion: v1
kind: Service
metadata:
  name: go-chi-demo
  labels:
    app: go-chi-demo
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      nodePort: 31300 # exposes service outside of cluster (for testing purposes)
  selector:
    app: go-chi-demo
