apiVersion: apps/v1
kind: Deployment
metadata:
  name: arangodb-deployment
  labels:
    app: arangodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arangodb
  template:
    metadata:
      labels:
        app: arangodb
    spec:
      containers:
        - name: arangodb
          image: arangodb:latest
          env:
            - name: ARANGO_ROOT_PASSWORD
              value: test
          ports:
            - containerPort: 8529
