apiVersion: v1
kind: Service
metadata:
  name: arangodb
  labels:
    app: arangodb
spec:
  type: NodePort
  ports:
    - port: 8529
      protocol: TCP
      nodePort: 31529 # exposes service outside of cluster (for testing purposes)
  selector:
    app: arangodb
