name: Delete Old Folders

on:
  push:
    branches:
      gh-pages
  schedule:
    - cron: "0 0 * * *"

jobs:
  delete_old_folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Find old folders
        run: |
          find . -type d -name "folder_name*" -mtime +1 -print0 | xargs -0 -I {} echo "Deleting {}"
          find . -type d -name "folder_name*" -mtime +1 -print0 | xargs -0 rm -rf
        shell: bash
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "Delete old folders"
          git push
        shell: bash
