name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  playwright-e2e-test:
    name: Playwright E2E Test
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    defaults:
      run:
        working-directory: ./frontend
    env:
      REPORT_DIR: frontend/e2e/playwright-report
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:playwright
      - uses: actions/upload-artifact@v3
        if: always() # runs this step even if previous steps failed
        with:
          name: playwright-report
          # prepend frontend because upload-artifact does not use working-directory setting
          # see https://github.com/actions/upload-artifact/issues/232#issuecomment-964235360
          path: ${{ env.REPORT_DIR }}
          retention-days: 30
      - name: Set report name
        id: report_name
        if: always() # runs this step even if previous steps failed
        run: |
          echo "REPORT_NAME=report_$(date +%F)_${{ github.run_id }}" >> $GITHUB_OUTPUT
          echo "setting REPORT_NAME=report_$(date +%F)_${{ github.run_id }}"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: always() # runs this step even if previous steps failed
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ env.REPORT_DIR }}
          destination_dir: ${{ steps.report_name.outputs.REPORT_NAME }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
      - name: Echo Report URL to stdout
        if: always() # runs this step even if previous steps failed
        run: |
          echo "See the Playwright Report [here](https://wederer.github.io/go-chi-demo/${{ steps.report_name.outputs.REPORT_NAME }}).
          The report will take a few minutes to be online."
        shell: bash
      - name: Comment Report URL to PR
        uses: thollander/actions-comment-pull-request@v2
        if: always() && github.event_name == 'pull_request'
        with:
          message: |
            See the Playwright Report [here](https://wederer.github.io/go-chi-demo/${{ steps.report_name.outputs.REPORT_NAME }}).
            The report will take a few minutes to be online.
          comment_tag: gh-pages-report-url
